<a href="https://colab.research.google.com/github/riyash0109/MachineLearning/blob/main/NaiveBaye's.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as mtp 
import numpy as nm

data = pd.read_csv('/content/indian_airquality2.csv')
df = pd.DataFrame(data)

df3 = df[['pollutant_min' , 'pollutant_max' , 'pollutant_avg']].copy()
df3.head()
#importing the libraries
#reading the dataset 
#loading the dataset into the dataframe 
#making a new dataframe df3 which has only three columns polluatnt_min ,pollutant_max , pollutant_avg

pollutant_min  pollutant_max  pollutant_avg
0           69.0          109.0           86.0
1           82.0          138.0          105.0
2           10.0           42.0           19.0
3            4.0            5.0            4.0
4           16.0           42.0           27.0

In [ ]:
df3 = df3.dropna()
#droping the null values

In [ ]:
def categorise(row):  
    if row['pollutant_avg'] > 54:
        return 1
    else :
        return 0

df3['lable'] = df3.apply(lambda row: categorise(row), axis=1)
#making a class lable based on the pollutant_avg

In [ ]:
df3.head()
#displaying the head of the dataframe

pollutant_min  pollutant_max  pollutant_avg  lable
0           69.0          109.0           86.0      1
1           82.0          138.0          105.0      1
2           10.0           42.0           19.0      0
3            4.0            5.0            4.0      0
4           16.0           42.0           27.0      0

In [ ]:
from sklearn.preprocessing import StandardScaler
#importing sklearn and standard scaler

In [ ]:
scaler = StandardScaler()
#making a variable scaler which takes output from function standardscaler

In [ ]:
scaler.fit(df3.drop('lable', axis = 1))
#normalizing or standardizing the dataset

StandardScaler()

In [ ]:
scaled_features = scaler.transform(df3.drop('lable', axis = 1))
#storing in scaled features

In [ ]:
df4= pd.DataFrame(scaled_features,columns=df3.columns[:-1])
df3.head()

pollutant_min  pollutant_max  pollutant_avg  lable
0           69.0          109.0           86.0      1
1           82.0          138.0          105.0      1
2           10.0           42.0           19.0      0
3            4.0            5.0            4.0      0
4           16.0           42.0           27.0      0

In [ ]:
from sklearn.model_selection import train_test_split
#importing train_test_split from sklearn.model_selection

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(scaled_features,df3['lable'],test_size=0.30)
#making training data and testing data 

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
#transforming the testing and training data

In [ ]:
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)
#calling the gaussianNb function and storing the return value in classifier var

GaussianNB()

In [ ]:
y_pred = classifier.predict(x_test) 
y_pred
#predicting the classifier value

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,

In [ ]:
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)
#constructing a confusion matrix

In [ ]:
cm
#displaying the confusion matrix

array([[367,   8],
       [  8, 139]])

In [ ]:
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)
#predicting the accuracy store

Gaussian Naive Bayes model accuracy(in %): 96.93486590038314


In [ ]:
#knn

In [ ]:
x_train2 , x_test2 , y_train2 , y_test2 = train_test_split(scaled_features,df3['lable'],test_size=0.30)
#making training data and testing data 

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 1)
classifier.fit(x_train2, y_train2)

KNeighborsClassifier(p=1)

In [ ]:
y_pred2 = classifier.predict(x_test2)
from sklearn.metrics import confusion_matrix,accuracy_score
cm2 = confusion_matrix(y_test2, y_pred2)
ac2 = accuracy_score(y_test2,y_pred2)
cm2
#getting thr accuracy and confusion matrix

array([[372,   0],
       [  1, 149]])

In [ ]:
ac2
#printing the accuarcy score

0.9980842911877394

Accuracy from naive baye's algorithm is 96.3 and from knn is 98.8