<a href="https://colab.research.google.com/github/riyash0109/MachineLearning/blob/main/SVM_DT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score

In [ ]:
#Importing the dataset
df = pd.read_csv('Automobile_data.csv')
df.head()
df.shape   


(210, 27)

In [ ]:
df = df.dropna()

In [ ]:
df['aspiration'].unique()
#taking the label data

array(['std', 'turbo'], dtype=object)

In [ ]:
df['aspiration'].replace(['std', 'turbo'],[0,1] ,inplace=True)
#replacing the word data with numbers

In [ ]:
df = df.head(50)
#taking first 50 entries.

In [ ]:
#Dividing dataset into features(X) and label(y)
X = df[['engine-size','bore']]
y = df['aspiration']
X

engine-size  bore
0         130.0  3.47
1         130.0  3.47
2         152.0  2.68
3         109.0  3.19
4         136.0  3.19
5         136.0  3.19
6         136.0  3.19
7         136.0  3.19
8         131.0  3.13
9         131.0  3.13
10        108.0   3.5
11        108.0   3.5
12        164.0  3.31
13        164.0  3.31
14        164.0  3.31
15        209.0  3.62
16        209.0  3.62
17        209.0  3.62
18         61.0  2.91
19         90.0  3.03
20         90.0  3.03
21         90.0  2.97
22         90.0  2.97
23         98.0  3.03
24         90.0  2.97
25         90.0  2.97
26         90.0  2.97
27         98.0  3.03
28        122.0  3.34
29        156.0   3.6
30         92.0  2.91
31         92.0  2.91
32         79.0  2.91
33         92.0  2.91
34         92.0  2.91
35         92.0  2.91
36         92.0  2.92
37        110.0  3.15
38        110.0  3.15
39        110.0  3.15
40        110.0  3.15
41        110.0  3.15
42        110.0  3.15
43        111.0  3.31
44         90.0  3.03
45         90.0  3.03
46        119.0  3.43
47        258.0  3.63
48        258.0  3.63
49        326.0  3.54

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=45,stratify=y)
#If we specify random state as constant integer train data will be constant For every run otherwise.
#Train data will be changed for every run and accuracy will differ.

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
# SVC with linear kernel

C = 1.0  # SVM regularization parameter


In [ ]:
svc =SVC(kernel='linear', C=C)
svc.fit(X_train, y_train)


SVC(kernel='linear')

In [ ]:
Trainaccuracy = cross_val_score(svc,X_train,y_train,cv=5)
svc.fit(X_train,y_train)
print("Train model accuracy:", np.mean(Trainaccuracy))


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  UserWarning,


Train model accuracy: 0.9142857142857143


In [ ]:
y_pred1 = svc.predict(X_test)
print ('Accuracy of linear svm:', accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))


Accuracy of linear svm: 0.8666666666666667
[[13  0]
 [ 2  0]]


In [ ]:
# SVC with RBF kernel
# Gamma indicates the ‘spread’ of the kernel  that is decision region.
#Gamma is low, the decision region is very broad. 
#When gamma is high, the ‘decision boundary is high, which creates islands of decision-boundaries around data points

rbf_svc =SVC(kernel='rbf', gamma=0.8, C=C)  
rbf_svc.fit(X_train, y_train)
y_pred2 = rbf_svc.predict(X_test)
print ('Accuracy of rbf kernel:', accuracy_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))


Accuracy of rbf kernel: 0.9333333333333333
[[13  0]
 [ 1  1]]


In [ ]:
# SVC with polynomial (degree 3) kernel
poly_svc =SVC(kernel='poly', degree=5, C=C)
poly_svc.fit(X, y)
y_pred3 = poly_svc.predict(X_test)
print ('Accuracy of polynomial kernel:', accuracy_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))

grid = {

    'C':[0.01,0.1,1,10],
    'kernel' : ["linear","poly","rbf"],
    'degree' : [1,3,5,7],
    'gamma' : [0.01,1]
}
svm =SVC()
svm_cv = GridSearchCV(svm, grid)
svm_cv.fit(X_train,y_train)

print("Best Parameters:",svm_cv.best_params_)

#print("Train Score:",svm_cv.best_score_)
print("Test Score:",svm_cv.score(X_test,y_test))


Accuracy of polynomial kernel: 0.8666666666666667
[[13  0]
 [ 2  0]]


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  UserWarning,
